# These are supported funding model platforms

github: Replace with up to  GitHub Sponsors-enabled username 199119119
patreon:  Replace with a single Patreon username
open_collective:  Replace with a single Open Collective username
ko_fi: Replace with a single username
tidelift: Replace with a single Tidelift platform-name/package-name 199119119
community_bridge:  Replace with a single Community Bridge project-name 199119119
liberapay:  Replace with a single Liberapay username
issuehunt:  Replace with a single IssueHunt username
lfx_crowdfunding: Replace with a single project-name 199119119
polar: Replace with a single username
buy_me_a_coffee: Replace with a single username
custom: Replace with up to custom sponsorship URL.
